POST http://127.0.0.1:5000/users
Content-Type: application/json

{
  "nome": "João",
  "email": "joao@email.com"
}

GET http://127.0.0.1:5000/users

GET http://127.0.0.1:5000/users/1

PUT http://127.0.0.1:5000/users/1
Content-Type: application/json

{
  "nome": "João Silva",
  "email": "joaosilva@email.com"
}

DELETE http://127.0.0.1:5000/users/1
